const db = require('../database/db');

// ── Training data — fully synced with script.js COACH_TRAINING_DATA ──
const TRAINING_DATA = [
  { intent: 'greeting', phrases: ['hello','hi','hey','sup','yo','greetings','howdy','good morning','good evening','good afternoon','whats up','hey there','hi there','hiya','heyo'] },
  { intent: 'thanks', phrases: ['thanks','thank you','thx','appreciate it','cheers','thanks a lot','thank you so much','ty','tysm','much appreciated','thanks coach','thanks for the help','that helps a lot','great thanks'] },
  { intent: 'help', phrases: ['help','what can you do','how to use this','options','commands','what do you know','help me','i need help','show me what you can do','what are my options','how does this coach work','what should i ask','guide me','what topics can you help with'] },
  { intent: 'body_score', phrases: ['body score','score','composition score','overall score','score results','body score number','scored','body rating','score body composition','body analysis score','total score','score check','results score','score percentage'] },
  { intent: 'body_category', phrases: ['category','body category','classification','fall category','body type','body type category','category results','class body','am fat','am skinny','am fit','classify body','type body','body classification','ectomorph endomorph mesomorph'] },
  { intent: 'muscle_tone', phrases: ['muscle tone','muscle score','muscular','lean mass','muscles','toned','muscle definition','muscle amount','muscle analysis','good muscle','muscles results','muscular body','muscle mass','tone score'] },
  { intent: 'posture', phrases: ['posture','posture score','alignment','posture check','posture results','spine alignment','back alignment','standing straight','good posture','posture analysis','check posture','stand straight','posture ok','posture rating'] },
  { intent: 'bmi', phrases: ['bmi','body mass index','bmi check','bmi score','bmi results','body mass','bmi number','bmi calculation','calculate bmi','height weight ratio','bmi category','weight height','mass index','bmi value'] },
  { intent: 'confidence', phrases: ['confidence','accuracy','accurate','reliable','trust','confidence level','confident','accurate results','trust results','reliable results','margin error','precise','accuracy level','confidence score','trustworthy'] },
  { intent: 'goal', phrases: ['goal','fitness goal','objective','target','goal setting','recommend goal','set goal','current goal','change goal','goal recommendation','goal check','goal plan','fitness objective','training goal','goal advice'] },
  { intent: 'lose_weight', phrases: ['lose weight','fat loss','cut down','slim down','weight loss','burn fat','lean','shed weight','losing weight','lose fat','drop weight','leaner','lose belly fat','trim down','slimmer','shred fat'] },
  { intent: 'build_muscle', phrases: ['build muscle','gain muscle','bulk','bigger muscles','hypertrophy','gain mass','muscle gain','building muscle','gaining muscle','jacked','swole','muscle building','grow muscle','increase muscle mass','strength training size'] },
  { intent: 'improve_posture', phrases: ['fix posture','improve posture','better posture','straighten posture','posture tips','posture exercises','fixing posture','correct posture','posture correction','stop slouching','stand straighter','exercises posture','help posture','fix back posture'] },
  { intent: 'workout_general', phrases: ['workout','exercise','training','exercises','gym','gym exercises','workout tips','exercise recommendations','training advice','best exercises','workout advice','exercises suggestions','workout suggestions','exercise ideas'] },
  { intent: 'workout_frequency', phrases: ['often work','frequency','times per week','days per week','rest days','often train','rest days needed','workout schedule','training frequency','frequently exercise','days off','weekly schedule','sessions per week','training days'] },
  { intent: 'workout_reps', phrases: ['reps','sets','rep range','volume','sets and reps','rep range ideal','heavy weight','reps muscle growth','sets per exercise','training volume','reps strength','ideal rep range','sets per workout','reps and sets'] },
  { intent: 'cardio', phrases: ['cardio','running','hiit','aerobic exercise','endurance','treadmill','cycling','cardio needed','cardio amount','cardio recommendations','best cardio fat loss','jogging','interval training','cardio workout','aerobics'] },
  { intent: 'nutrition_general', phrases: ['nutrition','diet','eating','food','meal plan','eat healthy','nutrition tips','diet advice','eating habits','meal suggestions','food recommendations','healthy eating','eat after gym','diet plan','nutrition advice'] },
  { intent: 'protein', phrases: ['protein','protein amount','protein intake','protein target','protein goal','protein per day','daily protein','protein requirements','enough protein','protein sources','high protein foods','grams protein','protein needs','whey protein','protein shake'] },
  { intent: 'calories', phrases: ['calories','calorie','caloric intake','tdee','calorie count','calorie deficit','calorie surplus','daily calories','calorie target','calories per day','maintenance calories','caloric needs','calorie amount','energy intake','kcal'] },
  { intent: 'macros', phrases: ['macros','macronutrients','carbs','fats','macro split','macro ratio','carbs amount','fat intake','carbohydrate intake','macro breakdown','macros eat','macro targets','fat carbs protein ratio','macronutrient split'] },
  { intent: 'how_it_works', phrases: ['technology behind','explain technology','mediapipe','algorithm','ai work','tech behind','explain analysis','scanning technology','ai technology','explain algorithm','powers analysis','analysis done','works behind scenes','technology stack','ai powered'] },
  { intent: 'what_is_this', phrases: ['fix it app','explain app','app purpose','app overview','describe app','about fix it','explain fix it','purpose app','fix it overview','fix it tool','about app','app description','app info','fix it features'] },
  { intent: 'identity', phrases: ['coach name','introduce yourself','coach identity','name coach','yourself introduction','r u ai','real person','ai coach','human or ai','talking to ai','bot or human','call you','coach info','ai or human','your identity'] },
  { intent: 'workout_plan', phrases: ['plan workout','create routine','design program','workout plan','training plan','exercise plan','build workout','routine plan','weekly workout plan','plan workouts','create training program','setup workout plan','workout plan needed','custom workout'] },
  { intent: 'cycle_workout', phrases: ['period','menstrual','menstruation','cycle','monthly cycle','on my period','time of month','that time','cramps','pms','hormones','menstrual cycle','period workout','workout on period','exercise during period','train on period','period cramps','cycle training','hormone cycle','low energy period','period fatigue','menstrual pain'] },
  { intent: 'cycle_for_other', phrases: ['for my partner','for partner','for my wife','for my girlfriend','for my friend','for a friend','for someone else','for another person','for her','for them','for my client','for a client','yes for someone','yes partner','yes friend','yes client'] },
  { intent: 'explain_upload', phrases: ['upload screen','upload photo','upload image','how upload','upload section','photo upload','take photo','camera upload','upload page','first screen','start screen','upload step','add photo','submit photo','image upload','photo capture','scan body'] },
  { intent: 'explain_results', phrases: ['results screen','results page','results tab','results section','explain results','show results','results mean','results overview','analysis results','body results','results display','score screen','main results','results data','results dashboard','fitness results','analysis overview'] },
  { intent: 'explain_breakdown', phrases: ['breakdown screen','breakdown page','breakdown tab','breakdown section','explain breakdown','detailed breakdown','body breakdown','breakdown view','zone breakdown','breakdown data','detailed analysis','breakdown scores','breakdown metrics','body zones','zone analysis','detailed metrics','metric breakdown'] },
  { intent: 'explain_simulator', phrases: ['simulator screen','simulator page','simulator tab','simulator section','explain simulator','body simulator','lifestyle simulator','simulation','simulate changes','before after','transformation preview','simulator feature','simulator tool','predict changes','future body','visual projection','projection','body projection','visualize transformation'] },
  { intent: 'explain_workout_screen', phrases: ['workout screen','workout page','workout tab','workout section','explain workout screen','exercise screen','training screen','workout display','workout feature','workout recommendations screen','exercise page','workout guidance','workout area','workout player','guided workout','exercise player','workout timer'] },
  { intent: 'explain_nutrition_screen', phrases: ['nutrition screen','nutrition page','nutrition tab','nutrition section','explain nutrition screen','meal screen','diet screen','nutrition display','nutrition feature','food screen','nutrition guidance screen','macro screen','calorie screen','meal plan screen','nutrition area','nutrition visualization','meal guidance','food guidance'] },
  { intent: 'explain_progress_screen', phrases: ['progress screen','progress page','progress tab','progress section','explain progress','gamification screen','achievements screen','badges screen','streak screen','xp screen','level screen','progress tracker','progress feature','progress display','progress dashboard','gamification','achievement badges','workout streak','level system','ranking system'] },
  { intent: 'explain_scan_history', phrases: ['scan history','history','past scans','previous scans','compare scans','comparison','compare progress','progress comparison','side by side','before and after','scan timeline','analysis history','saved scans','compare analyses','old scans','past analyses'] },
  { intent: 'app_features', phrases: ['features','app features','all features','list features','screens','all screens','different screens','explain screens','tabs','all tabs','different tabs','explain tabs','sections','all sections','app sections','overview','full overview','everything app does','capabilities','app capabilities','walkthrough','app modules','all modules','feature list','tour'] },
  { intent: 'explain_body_comp', phrases: ['body composition','composition','body fat percentage','lean mass ratio','fat mass','body fat','composition analysis','composition mean','body proportion','proportions analysis','composition section','composition feature','composition metric','fat percentage','lean mass','body mass composition'] },
  { intent: 'explain_muscle_dist', phrases: ['muscle tone distribution','muscle distribution','tone distribution','muscle map','muscle regions','muscle areas','muscle per region','upper body muscle','lower body muscle','muscle balance','muscle symmetry','muscle groups','muscle analysis','muscle breakdown','tone breakdown','muscle development areas'] },
  { intent: 'explain_posture_analysis', phrases: ['posture analysis','posture assessment','posture detection','spine analysis','alignment analysis','posture measurement','posture feature','posture check feature','shoulder alignment','head position analysis','hip alignment','posture evaluation','posture tracking','alignment check','spine check'] },
  { intent: 'explain_body_zones', phrases: ['body zones','zone analysis','body zone map','zone breakdown','body regions','body areas','zone scores','zone assessment','body zone feature','region analysis','area analysis','zone map','upper body zone','lower body zone','core zone','zone distribution'] },
  { intent: 'explain_fitness_index', phrases: ['fitness index','fitness score','overall fitness','fitness rating','fitness level','fitness grade','fitness number','fitness metric','fitness indicator','index score','fitness assessment','overall index','fitness measurement','fitness evaluation'] },
  { intent: 'explain_workout_player', phrases: ['workout player','exercise player','guided session','follow along','workout timer','exercise timer','rep counter','exercise tracker','workout guide','workout follow','play workout','start workout','guided exercise','workout mode','training player'] },
  { intent: 'explain_streaks_badges', phrases: ['streak','streaks','my streak','workout streak','daily streak','streak count','current streak','badge','badges','my badges','achievement','achievements','my achievements','badge collection','achievement list','streak counter','reward system','unlock badge','earn badge','streak broken','keep streak','milestone badge','achievement unlocked'] },
  { intent: 'explain_confidence_indicator', phrases: ['confidence indicator','confidence feature','input quality','analysis quality','scan quality','photo quality score','quality indicator','quality assessment','quality meter','quality check','input quality guidance','image quality','accuracy indicator','precision indicator','quality feature'] },
  { intent: 'explain_visual_age', phrases: ['visual age','age estimate','estimated age','apparent age','age prediction','age score','years younger','years older','age result','age calculation','age feature','look younger','look older','age assessment','biological age'] },
  { intent: 'explain_symmetry', phrases: ['symmetry','symmetry score','body symmetry','proportion balance','proportions','lean mass index','shoulder waist ratio','body proportions','balanced body','body ratio','proportion score','body balance','left right balance','muscle symmetry score'] },
  { intent: 'explain_ai_reasoning', phrases: ['ai reasoning','why ai thinks','explainability','explain why','ai explanation','reasoning behind','why this score','how ai decided','analysis reasoning','why ai','explain toggle','reasoning toggle','ai logic','why thinks this','explanation feature'] },
  { intent: 'explain_scenarios', phrases: ['lifestyle scenarios','scenarios','active lifestyle','sedentary scenario','intensive training scenario','nutrition optimization scenario','scenario cards','projected impact','impact summary','lifestyle choices','lifestyle options','scenario comparison','scenario selection','lifestyle change','projected changes'] },
  { intent: 'explain_weekly_routine', phrases: ['weekly routine','weekly plan','training split','weekly training','training plan generator','push pull legs','upper lower split','full body split','bro split','training days','weekly schedule','muscle coverage','day selector','rest day plan','generate plan','custom routine'] },
  { intent: 'explain_todays_routine', phrases: ['todays routine','today routine','daily routine','recommended workout','todays workout','today workout','daily workout','routine today','suggested workout','current routine','workout recommendation today','daily session','today session','planned workout'] },
  { intent: 'explain_food_recognition', phrases: ['food recognition','snap meal','food scanner','food photo','food camera','scan food','food detection','food ai','meal scanner','food analyzer','snap your meal','food upload','food identification','calorie scanner','meal photo','food estimate'] },
  { intent: 'explain_meal_plan', phrases: ['meal plan','meal planner','meal plan generator','personalized meals','daily meals','meal suggestions','meal recommendations','meal prep','dietary preference','vegetarian plan','high protein plan','low carb plan','meals per day','generate meals','custom meal plan'] },
  { intent: 'explain_daily_macros', phrases: ['daily macro targets','macro targets','macro bars','macro chart','macro circle','daily calories target','calorie target','protein target','carb target','fat target','on track percentage','macro progress','macro display','daily targets','nutrition targets display'] },
  { intent: 'explain_nutrition_insights', phrases: ['nutrition insights','protein timing','meal frequency','hydration goal','hydration target','water intake','eating schedule','meal timing','nutrient timing','nutrition tips display','science tips nutrition','hydration recommendation','eating frequency','water goal','nutrition science tips'] },
  { intent: 'explain_exercise_filters', phrases: ['exercise filters','home exercises','gym exercises','weak areas filter','workout filter','home gym filter','experience level','beginner intermediate advanced','difficulty level','exercise difficulty','filter exercises','sort exercises','exercise categories','workout categories','home workout filter'] },
  { intent: 'explain_themes', phrases: ['themes','theme picker','dark mode','light mode','color theme','change theme','app theme','charcoal theme','ivory theme','midnight theme','ocean theme','lavender theme','appearance','color scheme','switch theme','visual theme'] },
  { intent: 'explain_body_silhouette', phrases: ['body silhouette','body diagram','body visualization','body outline','body map','silhouette diagram','body image display','body figure','avatar display','body visual','body shape diagram','zone labels','shoulder label','core label','body drawing'] },
  { intent: 'explain_coach_personas', phrases: ['coach personas','persona modes','encouraging mode','planner mode','explainer mode','funny mode','coach styles','coach personalities','switch persona','different coaches','coach types','persona selection','coaching style','change persona','persona buttons'] },
  { intent: 'explain_bmr_tdee', phrases: ['bmr','tdee','basal metabolic rate','total daily energy expenditure','metabolic rate','metabolic card','metabolism calculator','mifflin st jeor','bmr calculator','tdee calculator','what is bmr','what is tdee','how calories calculated','recalculate macros','calorie formula','calorie recalculate'] },
  { intent: 'explain_daily_habits', phrases: ['daily habits','habit tracker','habits card','habit score','habit ring','daily score','check in habit','checkin','habits tracker','daily habit ring','habit completion','habit streak','five habits','5 habits','daily habits score'] },
  { intent: 'explain_sleep_tracker', phrases: ['sleep tracker','sleep log','log sleep','sleep hours','sleep quality','recovery score','sleep recovery','sleep bar chart','sleep history','sleep streak','sleep tracking','sleep bento','log sleep hours','sleep quality buttons','sleep bento cell'] },
  { intent: 'explain_weekly_report', phrases: ['weekly report','weekly grade','week report','report card','weekly card','weekly score','week grade','this weeks report','weekly summary','weekly review','weekly performance','week rating','weekly letter grade','weekly recap'] },
  { intent: 'explain_smart_insights', phrases: ['smart insights','insights card','personalized insights','ai insights','insight observations','smart observations','what are insights','fitness insights','data insights','insight analysis','insight generator','logged data insights'] },
  { intent: 'explain_calorie_balance', phrases: ['calorie balance','calories burned','burned calories','burned vs eaten','net calories','calorie deficit today','calories in calories out','exercise calories burned','daily calorie balance','calorie balance card','calories in out'] },
  { intent: 'explain_hydration_history', phrases: ['hydration history','water history','water heatmap','hydration heatmap','water streak','hydration streak','water average','water log history','hydration tracking history','past water intake','water best streak','water 7 day','hydration 7 day','water chart history'] },
  { intent: 'explain_progress_charts', phrases: ['progress charts','progress chart','weight chart','weight graph','progress graph','progress over time','track my progress','view progress','how do i track progress','trend over time','weight over time','see my progress','show my progress','progress tracking','data over time','stats over time','graphs','my graphs','show graph','view graph','trend chart','progress trend'] },
  { intent: 'explain_challenges', phrases: ['challenge','challenges','weekly challenge','weekly challenges','daily challenges','challenge feature','what are challenges','how do challenges work','complete challenge','challenge goal','challenge progress','finish challenge','challenge xp','challenge tab','current challenge','new challenge','challenge reward','active challenge','my challenges'] },
  { intent: 'explain_levels_xp', phrases: ['xp','level','levels','my level','my rank','rank','level up','xp points','experience points','how to level up','what is xp','earn xp','level system','rank up','level progress','next level','xp system','experience system','how xp works','level reward','leveling','rank system','xp score','rank title','my xp','experience','ranking','level badge'] },
  { intent: 'explain_weight_log', phrases: ['weight log','log weight','track weight','weight tracking','weight history','log my weight','add weight','weight entry','daily weight','weight diary','body weight log','weight today','how to log weight','weight records','log kg','track my weight'] },
  { intent: 'explain_goal_weight', phrases: ['goal weight','target weight','weight goal','set goal weight','how far to goal','progress to goal','goal tracking','kg remaining','weeks to goal','weight goal progress','reach my goal','edit goal','goal bar','goal card','weight target','set weight goal','pace to goal','estimated weeks','goal weight card'] },
  { intent: 'explain_food_log', phrases: ['food log','log food','log meal','food diary','meal log','add food','track food','food tracking','quick add food','log what i ate','daily food','food entry','nutrition log','log calories','food presets','food chip','quick add','meal entry','log my meals','food intake log','calorie log'] },
  { intent: 'explain_workout_splits', phrases: ['workout split','training split','push pull legs','ppl split','upper lower split','full body split','bro split','which split','split schedule','training schedule','workout schedule','split recommendation','what split should i do','how to split workouts','muscle group split','ppl','upper lower','full body routine','workout days','training days per week'] },
  { intent: 'explain_body_recomp', phrases: ['body recomposition','recomp','body recomp','lose fat gain muscle','recomposition','fat loss muscle gain','simultaneous fat loss','cut and bulk','recomp goal','what is recomposition','lose fat and build muscle','body transformation both','fat and muscle'] },
  { intent: 'explain_maintenance', phrases: ['maintenance','maintain weight','maintain fitness','maintain muscle','maintenance calories','how to maintain','maintaining weight','stay at current weight','keep my weight','weight maintenance','maintain phase','cut to maintenance','maintenance phase'] },
  { intent: 'explain_workout_history', phrases: ['workout history','exercise history','past workouts','previous workouts','workout log','exercise log','logged workouts','training history','workout sessions','completed workouts','workout record','session history','my workouts','workouts done','training log'] },
  { intent: 'explain_personal_records', phrases: ['personal records','personal record','pr','prs','personal best','pb','one rep max','1rm','max lift','best lift','strength record','record lift','lift pr','exercise pr','new pr','beat my pr','set a pr','my prs','my records'] },
  { intent: 'explain_body_measurements', phrases: ['body measurements','measurements','measure','body measuring','chest measurement','waist measurement','hip measurement','arm measurement','measure body','log measurements','measurement tracker','body tape','tape measure','circumference','body circumference','track measurements','measurement history'] },
  { intent: 'explain_account', phrases: ['my account','account settings','edit profile','update profile','change name','update email','change my email','change password','delete account','account page','fitness profile editing','update my details','change my details','profile settings','personal settings','how to edit profile','how to update profile','user menu','account menu','profile editing','account modal'] },
  { intent: 'explain_optional_measurements', phrases: ['optional measurements','should i fill in measurements','body measurement inputs','why add measurements','measurements accurate','improve accuracy','how to measure','tape measure input','measurement fields','what are optional measurements','add chest measurement','input measurements','upload measurements','should i measure','do i need measurements','fill in measurements','measurement section'] },
  { intent: 'explain_export', phrases: ['export data','share card','share results','share workout','export results','download results','save results','share my results','export my data','share progress','how to export','how to share','export button','share button','download data','share analysis','export analysis','shareable card'] },
  { intent: 'explain_comparison', phrases: ['compare scans','scan comparison','compare results','progress comparison','compare progress','before and after scans','compare two scans','side by side comparison','comparison modal','how to compare','compare body scans','select two scans','scan history comparison','body scan comparison','before after comparison'] },
  { intent: 'explain_live_posture', phrases: ['live posture','posture check','posture monitor','real time posture','camera posture','live camera posture','posture feedback','live posture check','posture camera','posture detection','real-time posture','start posture check','posture monitoring','live analysis posture','camera based posture'] },
  { intent: 'explain_data_management', phrases: ['clear data','delete data','clear all data','data management','reset app','clear storage','start over','wipe data','local storage','app data','delete local data','clear my data','storage usage','how much storage','data usage','clear app data','reset everything','storage info'] },
  { intent: 'explain_auth', phrases: ['login','log in','sign in','register','sign up','create account','forgot password','reset password','password reset','how to login','how to register','how to sign up','account creation','new account','verify email','email verification','authentication','how to create account','need an account','make an account'] },
];

const GOAL_LABELS = {
  lose_weight: 'fat loss',
  build_muscle: 'muscle building',
  maintain: 'maintenance',
  improve_posture: 'posture improvement',
  general: 'general fitness',
};

function detectIntent(text) {
  const lower = text.toLowerCase().trim();
  if (!lower) return null;

  let bestIntent = null;
  let bestScore = 0;

  for (const entry of TRAINING_DATA) {
    let score = 0;
    for (const phrase of entry.phrases) {
      if (lower === phrase) {
        score += 10;
      } else if (lower.includes(phrase)) {
        score += phrase.split(' ').length * 2;
      } else if (phrase.includes(lower)) {
        score += 3;
      }
    }
    if (score > bestScore) {
      bestScore = score;
      bestIntent = entry.intent;
    }
  }

  return bestScore >= 2 ? bestIntent : null;
}

async function buildContext(userId) {
  const scan = (await db.query(
    `SELECT s.*, r.*
     FROM analysis_scans s
     LEFT JOIN analysis_results r ON r.scan_id = s.id
     WHERE s.user_id = $1
     ORDER BY s.scan_date DESC LIMIT 1`,
    [userId]
  )).rows[0];

  const user = (await db.query(
    `SELECT gender, fitness_goal FROM users WHERE id = $1`, [userId]
  )).rows[0];

  return {
    bodyScore: scan?.body_comp_score ?? 'N/A',
    category: scan?.body_comp_category ?? 'unknown',
    grade: scan?.overall_grade ?? 'N/A',
    bodyType: scan?.body_type ?? 'unknown',
    muscleScore: scan?.muscle_tone_score ?? 'N/A',
    postureScore: scan?.posture_score ?? 'N/A',
    bmi: scan?.bmi ?? null,
    confidence: 'moderate',
    fitnessIndex: scan?.fitness_index ?? 'N/A',
    goal: user?.fitness_goal || 'general',
    gender: user?.gender || 'unknown',
  };
}

const RESPONSES = {
  encouraging: {
    greeting: (ctx) => `Hey there! I'm your coach, here to help you understand your results and crush your goals. Ask me anything about your body score, workouts, or nutrition!`,
    thanks: (ctx) => `You're welcome! Keep pushing forward -- you're doing great things for yourself.`,
    help: (ctx) => `I can help with lots of things! Try asking about your body score, muscle tone, posture, workouts, nutrition, or any screen in the app. Just type naturally -- I'll figure out what you need!`,
    identity: (ctx) => `I'm your Fix-it coach! I'm here to help you understand your analysis results, plan workouts, and guide your nutrition. Think of me as your personal fitness companion!`,
    body_score: (ctx) => `Your body composition score is ${ctx.bodyScore}/100, putting you in the "${ctx.category}" category. Grade: ${ctx.grade}. That's a real starting point to build from!`,
    body_category: (ctx) => `You're classified as "${ctx.category}" with a body type of "${ctx.bodyType}". This is based on your skeletal proportions and estimated composition.`,
    muscle_tone: (ctx) => `Your muscle tone score is ${ctx.muscleScore}%. Consistent training will push this number up -- every workout counts!`,
    posture: (ctx) => `Your posture score is ${ctx.postureScore}/100. Good posture makes you look and feel better -- and it's very trainable!`,
    bmi: (ctx) => ctx.bmi ? `Your BMI is ${ctx.bmi}. Remember, BMI is just one data point. Your full body score of ${ctx.bodyScore} gives a more complete picture!` : `You haven't entered your height and weight yet, so BMI isn't calculated yet.`,
    confidence: (ctx) => `The analysis confidence is "${ctx.confidence}". Boost it by using a clear, well-lit front-facing photo and entering your height and weight.`,
    goal: (ctx) => `Your current goal is ${GOAL_LABELS[ctx.goal] || 'general fitness'}. All your workout and nutrition recommendations are tailored to this!`,
    lose_weight: (ctx) => `For fat loss, aim for a 300-500 cal/day deficit, keep protein high (around 1g per pound of body weight), and add resistance training to preserve muscle. Consistency is everything!`,
    build_muscle: (ctx) => `To build muscle: slight calorie surplus (200-300 extra cal/day), plenty of protein (0.8-1g per lb), and progressive overload in your training. Sleep is when you actually grow!`,
    improve_posture: (ctx) => `To improve posture: strengthen your upper back (rows, face pulls), stretch your chest and hip flexors. Wall angels are a great daily exercise! Your posture score is ${ctx.postureScore}/100.`,
    workout_general: (ctx) => `Check the Workout screen for your tailored exercise plan based on your body score of ${ctx.bodyScore} and ${ctx.bodyType} build!`,
    workout_plan: (ctx) => `Based on your ${ctx.category} profile (score: ${ctx.bodyScore}), check the Workout screen for your personalized progressive program!`,
    workout_frequency: (ctx) => `For ${GOAL_LABELS[ctx.goal] || 'fitness'}, 3-5 training days per week works well. Rest days are when growth happens -- don't skip them!`,
    workout_reps: (ctx) => `Rep ranges: Strength 3-5, Muscle growth 8-12, Endurance 15-20. Mixing ranges is great for ${GOAL_LABELS[ctx.goal] || 'general fitness'}!`,
    cardio: (ctx) => `2-3 cardio sessions per week, 20-30 minutes each. Mix steady-state with one HIIT session for best results!`,
    nutrition_general: (ctx) => `Nutrition is huge for ${GOAL_LABELS[ctx.goal] || 'your goal'}! Check the Nutrition screen for personalized targets. Consistency beats perfection every time.`,
    protein: (ctx) => `Protein is the most important macro for body composition. Aim for 0.7-1g per pound of body weight daily. Chicken, eggs, fish, Greek yogurt -- all solid choices!`,
    calories: (ctx) => `Calories determine your direction -- fat loss: 300-500 deficit. Muscle gain: 200-300 surplus. Check your Nutrition screen for personalized targets!`,
    macros: (ctx) => `Set protein first (0.8-1g/lb), then fat (0.3-0.4g/lb), then fill remaining calories with carbs. Simple and effective!`,
    how_it_works: (ctx) => `This app uses MediaPipe Pose AI to detect 33 skeletal landmarks on your photo. It calculates body ratios to estimate composition. It's approximate but great for tracking progress!`,
    what_is_this: (ctx) => `Fix-it is a body composition analysis app! Upload a photo and AI estimates your body score, muscle tone, posture and more. All free, all in-browser!`,
    cycle_workout: (ctx) => `During your period, it's totally fine to train! Lower intensity during the first 1-2 days if you have cramps. Light cardio and stretching can actually help with discomfort. Listen to your body!`,
    cycle_for_other: (ctx) => `Happy to help! The principles are the same -- photo upload, body analysis, personalized recommendations. Have them go through the upload flow for their own results.`,
    explain_upload: (ctx) => `The Upload screen is where your journey starts! Take or upload a front-facing photo in good lighting. The better the photo quality, the more accurate your analysis will be.`,
    explain_results: (ctx) => `The Results screen shows your full body composition breakdown -- body score, category, grade, muscle tone, posture, BMI, and more. It's your fitness snapshot!`,
    explain_breakdown: (ctx) => `The Breakdown screen dives deep into your body zones -- upper body, core, lower body -- with individual scores and what they mean for your goals.`,
    explain_simulator: (ctx) => `The Simulator shows a projected transformation based on your current data and goal. Adjust the timeline to see what consistent effort could achieve!`,
    explain_workout_screen: (ctx) => `The Workout screen gives you personalized exercises based on your body analysis. Filter by home/gym, difficulty, and muscle focus. Tap any exercise to start a guided session!`,
    explain_nutrition_screen: (ctx) => `The Nutrition screen shows your daily macro targets, a food log, meal suggestions, and nutrition science tips -- all personalized to your body data and goal.`,
    explain_progress_screen: (ctx) => `The Progress screen is your command center! Daily Habits, Weekly Report Card, Sleep Tracker, Smart Insights, Progress Charts, streaks, badges, XP, level system, and scan history -- all in one place.`,
    explain_scan_history: (ctx) => `Scan History saves every body analysis you do. Tap any two scans to compare them side-by-side and see exactly how your metrics have changed over time!`,
    app_features: (ctx) => `Fix-it has 7 main screens: Upload (photo scan), Results (your body score), Breakdown (zone detail), Simulator (transformation preview), Workout (guided exercises), Nutrition (macro tracking), and Progress (gamification + history). Ask me about any of them!`,
    explain_body_comp: (ctx) => `Body composition is the ratio of fat mass to lean mass in your body. Your score of ${ctx.bodyScore}/100 reflects your overall composition -- the higher, the more favorable your lean-to-fat ratio.`,
    explain_muscle_dist: (ctx) => `Muscle tone distribution maps which regions of your body have the most developed muscle. It helps identify imbalances so you can train smarter and more symmetrically.`,
    explain_posture_analysis: (ctx) => `Posture analysis measures your shoulder alignment, spine position, and hip balance from your photo. A score of ${ctx.postureScore}/100 -- improving this improves both looks and injury prevention!`,
    explain_body_zones: (ctx) => `Body zones break your physique into upper body, core, and lower body sections, each with its own score. It's a roadmap for where to focus your training energy.`,
    explain_fitness_index: (ctx) => `The Fitness Index (${ctx.fitnessIndex}) is a composite score combining your body composition, muscle tone, posture, and proportions into one overall fitness number.`,
    explain_workout_player: (ctx) => `The Workout Player guides you through exercises with animated demos, rep/set counters, and rest timers. Tap "Start" on any exercise to enter guided mode!`,
    explain_streaks_badges: (ctx) => `Streaks track consecutive days of logging in and working out. Badges are awarded for milestones like your first scan, hitting a 7-day streak, or trying every coach persona. Keep showing up!`,
    explain_confidence_indicator: (ctx) => `The confidence indicator shows how reliable your body analysis is. Better lighting, a front-facing full-body photo, and entering your height and weight all boost it.`,
    explain_visual_age: (ctx) => `Visual Age estimates how old your body composition "looks" based on fitness metrics. Great conditioning can make your body appear younger than your actual age!`,
    explain_symmetry: (ctx) => `Symmetry score measures how balanced your body proportions are -- shoulder-to-waist ratio, left-right muscle balance, and overall structural harmony.`,
    explain_ai_reasoning: (ctx) => `The AI Reasoning toggle shows WHY the app gave you each score. It explains which body ratios and landmark measurements drove each result -- full transparency!`,
    explain_scenarios: (ctx) => `Lifestyle Scenarios in the Simulator show projected body changes under different conditions: Active, Sedentary, Intensive Training, or Nutrition-Optimized. Compare them to find your ideal path!`,
    explain_weekly_routine: (ctx) => `The Weekly Routine generator builds a personalized training split based on your goal and how many days you want to train. Push/Pull/Legs, Upper/Lower, Full Body -- it designs it for you!`,
    explain_todays_routine: (ctx) => `Today's Routine shows your recommended workout for the day based on your training split. It adapts to your schedule so you always know what to train next.`,
    explain_food_recognition: (ctx) => `Snap Your Meal lets you photograph food and the AI estimates the calories and macros! It's the fastest way to log a meal without manually searching for everything.`,
    explain_meal_plan: (ctx) => `The Meal Plan generator creates a full day of meal suggestions personalized to your calorie and macro targets. Filter by dietary preference -- vegetarian, high protein, low carb, and more!`,
    explain_daily_macros: (ctx) => `Daily Macro Targets shows your calorie goal with protein, carbs, and fat progress bars. The circular chart shows your overall on-track percentage. Watch those bars fill up!`,
    explain_nutrition_insights: (ctx) => `Nutrition Insights gives science-backed tips: protein timing (spread across 4-5 meals), meal frequency (every 3-4 hours), and a personalized hydration goal. Small habits, big results!`,
    explain_exercise_filters: (ctx) => `Exercise filters let you narrow workouts by location (home or gym), experience level (beginner to advanced), and weak areas. Find exactly the right exercise for your situation!`,
    explain_themes: (ctx) => `Themes let you customize the app's look! Choose from Charcoal, Ivory, Midnight, Ocean, and Lavender in the Preferences menu. Find the vibe that keeps you coming back!`,
    explain_body_silhouette: (ctx) => `The Body Silhouette is a visual diagram showing your body zones with score labels overlaid. It gives you an intuitive, at-a-glance view of where your strengths and areas to work on are.`,
    explain_coach_personas: (ctx) => `There are 4 coach styles: Encouraging (supportive), Drill Sergeant (tough love), Scientific (evidence-based), and Casual (laid-back buddy). Switch anytime with the persona buttons at the top of the coach panel!`,
    explain_bmr_tdee: (ctx) => `BMR is your Basal Metabolic Rate -- calories burned at rest. TDEE is your Total Daily Energy Expenditure -- BMR plus activity. Your nutrition targets are built on your TDEE calculation!`,
    explain_daily_habits: (ctx) => `Daily Habits tracks 5 key behaviors every day: workout logged, food logged, water goal met, sleep logged, and coach consulted. Complete all 5 for a perfect daily score and keep that habit ring full!`,
    explain_sleep_tracker: (ctx) => `The Sleep Tracker logs your nightly hours and sleep quality. Good sleep is when your muscles actually repair and grow -- it's as important as training! Log it every morning.`,
    explain_weekly_report: (ctx) => `The Weekly Report Card grades your entire week -- workouts completed, nutrition consistency, sleep quality, and habit score. It's your weekly performance review in one letter grade!`,
    explain_smart_insights: (ctx) => `Smart Insights analyzes your logged data to surface patterns you might miss -- like consistently low sleep on certain days, or great hydration but poor meal logging. It's your personal data analyst!`,
    explain_calorie_balance: (ctx) => `Calorie Balance shows calories eaten vs. calories burned today, and your net calories. It's the clearest way to see if you're in a deficit (fat loss), surplus (muscle gain), or at maintenance.`,
    explain_hydration_history: (ctx) => `Hydration History shows your water intake over the past 7 days as a heatmap. See your hydration streak, daily average, and personal best. Consistent hydration dramatically affects energy and performance!`,
    explain_progress_charts: (ctx) => `Progress Charts visualize your data over time -- weight, sleep, activity, calories, body score, and BMI. Each tab shows a trend line so you can see exactly how you're improving!`,
    explain_challenges: (ctx) => `Challenges are weekly missions like "log 3 workouts" or "ask the coach 5 questions". Complete them to earn XP and level up faster! Check the Progress screen to see your active challenges.`,
    explain_levels_xp: (ctx) => `XP is earned by scanning, logging meals, completing challenges, and chatting with me! Accumulate XP to level up your rank. The higher your level, the more you've committed to your journey!`,
    explain_weight_log: (ctx) => `The Weight Log lets you record your weight daily so you can track trends over time. Head to the Progress screen and use the "Log today's weight" input to add an entry.`,
    explain_goal_weight: (ctx) => `The Goal Weight card shows your journey from starting weight to target, with a progress bar, kg remaining, estimated weeks, and your weekly pace. Set it in the Progress screen and log your weight regularly!`,
    explain_food_log: (ctx) => `The Food Log tracks what you eat and tallies your daily macros. Use it daily to stay on top of protein, carbs, and fats. Consistency in logging leads to consistency in results!`,
    explain_workout_splits: (ctx) => `Workout splits divide training by muscle group. Push/Pull/Legs, Upper/Lower, or Full Body -- check the Workout screen for your recommended split based on your goals and schedule!`,
    explain_body_recomp: (ctx) => `Body recomposition means losing fat while gaining muscle simultaneously! It's best for beginners or those returning after a break. Eat at maintenance, keep protein high, and train with progressive overload.`,
    explain_maintenance: (ctx) => `Maintenance means eating at your TDEE -- not gaining or losing weight. It's a great phase to consolidate muscle gains and give your body a break before the next cut or bulk.`,
    explain_workout_history: (ctx) => `Workout History logs every session you complete in the app! See your past workouts, how many sets and reps you did, and track consistency over time. Every logged session is progress documented!`,
    explain_personal_records: (ctx) => `Personal Records track your best lifts for each exercise -- your 1-rep max, heaviest set, or best performance. Every time you beat a previous record, it gets saved here. Watch them climb as you get stronger!`,
    explain_body_measurements: (ctx) => `Body Measurements lets you log your chest, waist, hips, and arms over time. Even when the scale doesn't move, shrinking waist and growing arm measurements tell the real story. Log every 2-4 weeks for the best trends!`,
    explain_account: (ctx) => `Your My Account section is in the user menu (tap your name or avatar in the top right)! You can update your display name, email, fitness profile details (height, weight, gender, goal, activity level), change your password, or delete your account. Keeping your fitness details accurate helps me give you better recommendations!`,
    explain_optional_measurements: (ctx) => `The optional measurements on the upload screen (chest, waist, hips, arms in cm) are absolutely worth filling in! They give the AI real body proportion data to complement the photo analysis, making your results much more accurate. Just grab a soft tape measure and measure at the widest point for each area!`,
    explain_export: (ctx) => `On the Results screen, tap "Export Data" to save your full analysis report, or "Share Card" to generate a shareable summary card — perfect for documenting progress! After a workout in the Player, "Share Workout" lets you share your session summary too. Show the world your hard work!`,
    explain_comparison: (ctx) => `The scan comparison feature is so motivating! Head to the Progress screen, scroll down to Scan History, select any two scans, and tap Compare. You'll see a side-by-side view of your body score, muscle tone, posture, and more — with clear change indicators. Watching those improvements is incredibly rewarding!`,
    explain_live_posture: (ctx) => `The Live Posture Check on the Workout screen is fantastic! Tap "Start Live Posture Check" and your camera activates for real-time posture feedback — it detects shoulder, spine, and hip alignment and shows correction cues live as you exercise. Great for perfecting form and preventing injury!`,
    explain_data_management: (ctx) => `The "Clear All Data" button is in the Danger Zone section of Profile Settings (tap your avatar → My Account, scroll to the bottom)! It removes locally stored session data, scan history, and logs for a fresh start. This only clears local data — your account info on the server stays safe!`,
    explain_auth: (ctx) => `Creating an account is quick! Click "Sign Up", enter your email, choose a password, add your display name, and verify your email. Already registered? Just log in. Forgot your password? Use "Forgot Password" to reset via email. Accounts keep your progress synced across sessions!`,
    default: (ctx) => `Great question! Try asking about your body score, workouts, nutrition, or any feature in the app. I'm here to help you get the most out of Fix-it!`,
  },

  drill_sergeant: {
    greeting: (ctx) => `Listen up! I'm your drill sergeant coach. No excuses, no shortcuts. Ask me what you need and let's get to WORK.`,
    thanks: (ctx) => `Don't thank me -- thank yourself when you see results. Now get back to work!`,
    help: (ctx) => `Ask me about your score, workouts, nutrition, or any feature. I don't sugarcoat. Let's go!`,
    identity: (ctx) => `I'm your no-nonsense fitness drill sergeant. I give it to you straight -- your score, workout plans, nutrition -- all of it. No excuses accepted!`,
    body_score: (ctx) => `Your score is ${ctx.bodyScore}/100. Grade: ${ctx.grade}. ${ctx.bodyScore < 50 ? 'We have WORK to do. No excuses!' : 'Not bad, but we can do better!'}`,
    body_category: (ctx) => `You're "${ctx.category}" with a ${ctx.bodyType} build. That's your starting line, not your finish line. Let's move!`,
    muscle_tone: (ctx) => `Muscle tone: ${ctx.muscleScore}%. ${ctx.muscleScore < 50 ? 'Weak. Time to hit the weights HARD.' : 'Decent, but there\'s always room for more.'}`,
    posture: (ctx) => `Posture: ${ctx.postureScore}/100. ${ctx.postureScore < 60 ? 'Stand up straight, soldier! Fix it.' : 'Acceptable. Keep it tight.'}`,
    bmi: (ctx) => ctx.bmi ? `BMI: ${ctx.bmi}. One number. Your score of ${ctx.bodyScore} tells the real story.` : `No BMI data. Enter your height and weight -- I need full intel!`,
    lose_weight: (ctx) => `Fat loss: eat less, move more, keep protein high. 300-500 calorie deficit, resistance training, DISCIPLINE. No magic pills.`,
    build_muscle: (ctx) => `Calorie surplus, heavy compound lifts, progressive overload, 7-9 hours sleep. EVERY. SINGLE. DAY. No excuses!`,
    improve_posture: (ctx) => `Posture: rows, face pulls, wall angels, daily. Stand like you mean it. Slouching is for the weak.`,
    workout_general: (ctx) => `Score ${ctx.bodyScore}? ${ctx.bodyScore < 40 ? 'Starting from the ground up. 3x/week, compound movements, NO skipping.' : 'Time to push harder. Progressive overload every week!'}`,
    workout_plan: (ctx) => `Check the Workout screen. Follow it. Don't skip days. That's your plan.`,
    workout_frequency: (ctx) => `3-5 days minimum. Rest days are NOT laziness -- they're strategy. But if you're resting more than training, that's a problem.`,
    workout_reps: (ctx) => `Compound lifts heavy (3-5 reps), isolation moderate (8-12 reps). Track every set. No phone scrolling between sets.`,
    cardio: (ctx) => `2-3 sessions per week. Mix HIIT and steady-state. No excuses about being tired -- that's when it counts most.`,
    nutrition_general: (ctx) => `You can't out-train a bad diet. Protein at every meal, vegetables, water. Check the Nutrition screen for your targets.`,
    protein: (ctx) => `Minimum 0.8g per pound of bodyweight. EVERY. SINGLE. DAY. Non-negotiable.`,
    calories: (ctx) => `Track your calories or stop complaining about results. That simple. Check the Nutrition screen.`,
    macros: (ctx) => `Protein first, always. Fat and carbs fill the rest. No processed junk. No excuses.`,
    how_it_works: (ctx) => `AI scans your photo, measures your skeleton, calculates your body ratios. The data doesn't lie. YOUR JOB is to change it.`,
    what_is_this: (ctx) => `Fix-it: body analysis, workout plans, nutrition tracking, gamification. Tools are here. Results depend on YOU.`,
    cycle_workout: (ctx) => `Listen to your body -- reduce intensity if needed, but don't quit entirely. Light movement helps more than rest during low-energy phases.`,
    cycle_for_other: (ctx) => `Same process. They upload their photo, get their analysis, follow their plan. No special treatment.`,
    explain_upload: (ctx) => `Upload screen: take a photo, front-facing, good lighting, full body. Good input = good output. Don't waste my time with bad photos.`,
    explain_results: (ctx) => `Results screen: your score, your grade, your numbers. This is your baseline. Now do something about it.`,
    explain_breakdown: (ctx) => `Breakdown: zone-by-zone scores. Upper body, core, lower body. Find your weakest zone and attack it.`,
    explain_simulator: (ctx) => `Simulator: see what you COULD look like if you actually put in the work. Let that image motivate you. Now go train.`,
    explain_workout_screen: (ctx) => `Workout screen: your exercises, your plan. Filter by location and level. Then DO THE WORK.`,
    explain_nutrition_screen: (ctx) => `Nutrition screen: your targets, your food log, your macros. Log everything. No exceptions.`,
    explain_progress_screen: (ctx) => `Progress screen: your streaks, badges, XP, challenges, scan history, weekly report. Data doesn't lie. What does yours say?`,
    explain_scan_history: (ctx) => `Scan history: every analysis you've done, side by side. Look at your old scans. Are you improving? If not, change something.`,
    app_features: (ctx) => `Upload. Analyze. Train. Eat right. Track progress. Repeat. That's the app. That's the process.`,
    explain_body_comp: (ctx) => `Body composition is the ratio that matters -- muscle vs. fat. Score ${ctx.bodyScore}. Are you happy with it? Then change it.`,
    explain_muscle_dist: (ctx) => `Muscle distribution shows where you're strong and where you're weak. Attack the weak zones. No balanced weakness allowed.`,
    explain_posture_analysis: (ctx) => `Posture score: ${ctx.postureScore}. Measured from your photo. Weak posture = injuries waiting to happen. Fix it.`,
    explain_body_zones: (ctx) => `Upper, core, lower -- each zone scored. Identify your weakness. Train it hard. Eliminate the gap.`,
    explain_fitness_index: (ctx) => `Fitness index: ${ctx.fitnessIndex}. Composite score. One number to beat every scan.`,
    explain_workout_player: (ctx) => `Workout player: animated demos, timers, rep counts. No excuse to not know the form. Hit Start and go.`,
    explain_streaks_badges: (ctx) => `Streaks and badges aren't trophies -- they're evidence of discipline. Every day you show up, that number goes up. Every day you skip, it resets.`,
    explain_confidence_indicator: (ctx) => `Confidence score tells you how good your analysis data is. Bad photo = bad data = bad plan. Do it right the first time.`,
    explain_visual_age: (ctx) => `Visual age: how old your body looks based on composition. Train hard and it drops. Slack off and it rises.`,
    explain_symmetry: (ctx) => `Symmetry score: imbalances get you injured. Fix them before they fix you.`,
    explain_ai_reasoning: (ctx) => `AI reasoning: shows exactly why you got each score. Read it, understand your weaknesses, and fix them. No hiding.`,
    explain_scenarios: (ctx) => `Scenarios: see what Active vs Sedentary vs Intensive training gets you. Choose your path. Then COMMIT to it.`,
    explain_weekly_routine: (ctx) => `Weekly routine: your training split. Follow it. Every muscle group gets hit. No favorites.`,
    explain_todays_routine: (ctx) => `Today's workout: it's on the Workout screen. Stop reading, start moving.`,
    explain_food_recognition: (ctx) => `Snap your meal, get the macros. No excuse to not log your food now.`,
    explain_meal_plan: (ctx) => `Meal plan is generated for you. Follow it. Meal prep on Sunday. Excuses are for people who don't want results.`,
    explain_daily_macros: (ctx) => `Daily macro targets: your numbers for today. Hit protein. Then the rest. Every single day.`,
    explain_nutrition_insights: (ctx) => `Nutrition insights: protein timing, meal frequency, hydration. Evidence-based. Follow it or explain why you're not getting results.`,
    explain_exercise_filters: (ctx) => `Filters: home or gym, beginner to advanced. No excuses about equipment. Home workouts work if you push hard enough.`,
    explain_themes: (ctx) => `Themes: pick one and get back to training. This isn't a fashion show.`,
    explain_body_silhouette: (ctx) => `Body silhouette: your zones visualized. See your weaknesses clearly. Now go eliminate them.`,
    explain_coach_personas: (ctx) => `4 coach styles. You picked me -- the one that tells you the truth. Good choice.`,
    explain_bmr_tdee: (ctx) => `BMR and TDEE are your calorie foundations. Know them. If you don't track against them, you're guessing. Stop guessing.`,
    explain_daily_habits: (ctx) => `5 habits: workout, food log, water, sleep, coach. Complete all 5 every day. No partial credit in fitness.`,
    explain_sleep_tracker: (ctx) => `Log your sleep every morning. 7-9 hours is non-negotiable for recovery. Skimping on sleep is sabotaging your results.`,
    explain_weekly_report: (ctx) => `Weekly report card: your grade for the week. Anything below a B means you left results on the table. Do better next week.`,
    explain_smart_insights: (ctx) => `Smart insights catches patterns in your data. Pay attention -- it's telling you where you're failing without realizing it.`,
    explain_calorie_balance: (ctx) => `Calories in vs. calories out. This number determines everything. Know it. Control it.`,
    explain_hydration_history: (ctx) => `Hydration history: your water intake over time. Dehydration kills performance. See the streak. Keep it going.`,
    explain_progress_charts: (ctx) => `Progress charts: your data over time. Is the trend line going the right direction? If not, something needs to change. TODAY.`,
    explain_challenges: (ctx) => `Weekly challenges are your ORDERS. Log workouts, ask coach questions, hit targets. Complete them or accept you didn't push hard enough.`,
    explain_levels_xp: (ctx) => `XP tracks your commitment. Every action earns it. High level means you've done the work. Low level means you haven't.`,
    explain_weight_log: (ctx) => `Log your weight EVERY DAY. One number, one habit. If you can't do that, how are you going to transform your body?`,
    explain_goal_weight: (ctx) => `Goal weight: your target. You either hit it or you don't. Track it, log your weight, watch the weeks tick down.`,
    explain_food_log: (ctx) => `Log every meal. Every snack. Every bite. If you're not logging, you're guessing. Guessing doesn't get results.`,
    explain_workout_splits: (ctx) => `Your split is your battle plan. Pick Push/Pull/Legs, Upper/Lower, or Full Body -- and EXECUTE it every week.`,
    explain_body_recomp: (ctx) => `Recomp: maintenance calories, high protein, heavy lifting. Hard mode. If you're disciplined enough, you'll get there.`,
    explain_maintenance: (ctx) => `Maintenance phase: keep training hard, keep protein high. This isn't a vacation -- it's consolidation before the next push.`,
    explain_workout_history: (ctx) => `Workout History: every session logged, no excuses. If it's not in there, it didn't happen. Check your consistency. Are you proud of what you see?`,
    explain_personal_records: (ctx) => `Personal Records: your best lifts. Every number is a target to beat. If your PRs aren't moving up, your training isn't hard enough.`,
    explain_body_measurements: (ctx) => `Body Measurements: tape doesn't lie. Log chest, waist, hips, arms every 2-4 weeks. Numbers going the right direction? Good. Wrong direction? Adjust.`,
    explain_account: (ctx) => `My Account is in the user menu — top right. Update your name, email, fitness stats, and password. Keep that height, weight, and goal current. Outdated data = bad recommendations. Fix it.`,
    explain_optional_measurements: (ctx) => `Don't skip the optional measurements! Chest, waist, hips, arms — fill them all in. More data = more accurate plan. Grab a tape measure, measure at the widest point, enter the numbers. No excuses.`,
    explain_export: (ctx) => `Results screen: Export Data saves your full report. Share Card creates a shareable visual — post your progress, stay accountable. Share Workout after sessions — let it be on record. Accountability is training fuel.`,
    explain_comparison: (ctx) => `Scan History is in the Progress screen. Select two scans, hit Compare. Side by side: body score, muscle tone, posture — everything. If the numbers aren't improving, adjust your plan. Data doesn't lie.`,
    explain_live_posture: (ctx) => `Live Posture Check is in the Workout screen. Hit it, use your camera, get real-time form monitoring. Shoulders, spine, hips — if your alignment is off, it tells you. No sloppy form on my watch.`,
    explain_data_management: (ctx) => `"Clear All Data" is in Danger Zone — Profile Settings (My Account), scroll to bottom. Wipes local sessions, scan history, logs. Know what you're deleting before you hit it. Server data stays.`,
    explain_auth: (ctx) => `Sign Up — email, password, display name, verify email. Done. Existing account? Log in. Forgot password? Reset it. No excuses for not having an account — it keeps your data safe and synced.`,
    default: (ctx) => `Stay focused! Ask me about your score, workouts, or nutrition. No time for chitchat -- let's TRAIN!`,
  },

  scientific: {
    greeting: (ctx) => `Hello. I'm your science-based fitness advisor. I'll provide evidence-informed analysis of your body composition, training, and nutritional data. What would you like to explore?`,
    thanks: (ctx) => `You're welcome. Data-driven decisions lead to optimal outcomes. Continue consulting as needed.`,
    help: (ctx) => `I can analyze: body composition metrics, muscle development, postural alignment, exercise programming, nutritional biochemistry, and the underlying AI technology. What interests you?`,
    identity: (ctx) => `I'm a science-based fitness advisor. My responses are grounded in exercise physiology, nutritional science, and biomechanics. I reference your analysis data for personalized insights.`,
    body_score: (ctx) => `Your composite body score is ${ctx.bodyScore}/100 (${ctx.category}), grade ${ctx.grade}. This index aggregates skeletal proportion ratios, estimated lean mass distribution, and postural alignment data.`,
    body_category: (ctx) => `Classification: "${ctx.category}", somatotype approximation: "${ctx.bodyType}". Derived from shoulder-to-hip ratio, waist estimation, and limb proportion analysis.`,
    muscle_tone: (ctx) => `Muscle tone index: ${ctx.muscleScore}%. This estimates lean mass distribution based on limb circumference ratios relative to skeletal frame size.`,
    posture: (ctx) => `Postural alignment score: ${ctx.postureScore}/100. Metrics include glenohumeral symmetry, cervical forward displacement, and pelvic tilt estimation via landmark triangulation.`,
    bmi: (ctx) => ctx.bmi ? `BMI: ${ctx.bmi} kg/m². Note: BMI has limited diagnostic value as it doesn't differentiate adipose tissue from lean mass. Your composite score (${ctx.bodyScore}) provides a more nuanced assessment.` : `Insufficient anthropometric data for BMI calculation. Height and weight input required.`,
    confidence: (ctx) => `Confidence level: "${ctx.confidence}". Influenced by image resolution, landmark detection accuracy, and available anthropometric data. Higher confidence = more reliable estimates.`,
    goal: (ctx) => `Current goal: ${GOAL_LABELS[ctx.goal] || 'general fitness'}. Programming variables including volume, intensity, and macronutrient distribution are optimized for this objective.`,
    lose_weight: (ctx) => `Optimal fat loss protocol: 300-500 kcal/day deficit, protein 1.6-2.2g/kg lean mass, resistance training 3-4x/week for lean mass preservation. Target rate: 0.5-1% bodyweight/week.`,
    build_muscle: (ctx) => `Hypertrophy protocol: 200-350 kcal/day surplus, protein 1.6-2.2g/kg, 10-20 sets/muscle group/week, progressive overload as primary stimulus.`,
    improve_posture: (ctx) => `Posture score: ${ctx.postureScore}/100. Evidence-based interventions: posterior chain strengthening (rows, face pulls), thoracic mobility work, hip flexor lengthening.`,
    workout_general: (ctx) => `Based on your composite score (${ctx.bodyScore}) and somatotype (${ctx.bodyType}), programming should prioritize compound movements with systematic progressive overload.`,
    workout_plan: (ctx) => `Evidence-based programming for your ${ctx.category} profile: periodized resistance training with progressive overload. Consult the Workout module for specific programming.`,
    workout_frequency: (ctx) => `Optimal frequency for ${GOAL_LABELS[ctx.goal] || 'fitness'}: 3-5 sessions/week. Each muscle group should be stimulated 2x/week for maximal hypertrophy per current evidence.`,
    workout_reps: (ctx) => `Rep ranges by adaptation: Strength 1-5 (neural adaptation), Hypertrophy 6-12 (metabolic stress + mechanical tension), Endurance 15-20+ (oxidative). Volume = sets × reps × load.`,
    cardio: (ctx) => `Cardiovascular programming: 2-3 sessions/week. Zone 2 steady-state (60-70% HRmax) plus 1 HIIT session. VO2 max improvements require systematic progressive overload.`,
    nutrition_general: (ctx) => `Nutritional periodization aligned with your ${GOAL_LABELS[ctx.goal] || 'fitness'} objective. Macronutrient distribution should reflect training demands and recovery requirements.`,
    protein: (ctx) => `Current evidence supports 1.6-2.2g protein/kg bodyweight for active individuals. Leucine threshold (~2.5g) per meal optimizes muscle protein synthesis signaling.`,
    calories: (ctx) => `Energy balance is the primary determinant of body mass change. TDEE estimation + systematic tracking provides the foundation. Metabolic adaptation requires periodic reassessment.`,
    macros: (ctx) => `Macronutrient hierarchy: protein (1.6-2.2g/kg) → fat (0.5-1g/kg for hormonal function) → carbohydrates (fills remaining calories, scaled to training volume).`,
    how_it_works: (ctx) => `MediaPipe Pose detects 33 skeletal landmarks. Body composition is estimated via: shoulder-to-hip ratio (V-taper), limb circumference proxies, edge detection for width measurement. Outputs are probabilistic estimates with defined confidence intervals.`,
    what_is_this: (ctx) => `Fix-it is an AI-powered body composition estimation platform using computer vision (MediaPipe Pose) for skeletal landmark detection and derived body metric calculation.`,
    cycle_workout: (ctx) => `Menstrual cycle-adapted training: follicular phase (days 1-14) generally permits higher intensity. Luteal phase (days 15-28) may benefit from reduced load due to elevated progesterone and potential fatigue.`,
    cycle_for_other: (ctx) => `The analysis pipeline is identical regardless of the subject. Individual analysis data will reflect their specific anthropometrics and composition.`,
    explain_upload: (ctx) => `Upload phase: image quality directly impacts landmark detection accuracy. Optimal conditions: front-facing, full-body, neutral background, even lighting, minimal clothing occlusion.`,
    explain_results: (ctx) => `Results screen: displays primary metrics -- body composition score, category, grade, muscle tone index, postural score, BMI, and fitness index. All derived from MediaPipe Pose landmark analysis.`,
    explain_breakdown: (ctx) => `Breakdown screen: segmental body composition analysis. Upper body, core, and lower body zones each receive individual scores based on limb-to-trunk ratio calculations.`,
    explain_simulator: (ctx) => `The Simulator applies research-backed transformation rates: 0.5-1 lb/week fat loss, 0.25-0.5 lb/week muscle gain. Projects estimated changes based on goal and timeline selection.`,
    explain_workout_screen: (ctx) => `Workout screen: exercise recommendations are filtered by training goal (${GOAL_LABELS[ctx.goal] || 'fitness'}), environment (home/gym), and experience level. Exercise player includes form guidance and progressive loading suggestions.`,
    explain_nutrition_screen: (ctx) => `Nutrition screen: displays TDEE-based calorie and macronutrient targets. Food log enables daily intake tracking. Insights based on nutrient timing and meal frequency research.`,
    explain_progress_screen: (ctx) => `Progress screen: longitudinal data tracking including body score trends, anthropometric measurements, sleep data, behavioral habit adherence, and gamification metrics (XP, level, challenges).`,
    explain_scan_history: (ctx) => `Scan history: chronological record of all body analyses. Side-by-side comparison quantifies change across all metrics -- statistically meaningful trend analysis requires minimum 3-4 data points.`,
    app_features: (ctx) => `Platform modules: body composition analysis (CV-based), transformation simulation (rate-based projection), exercise programming, nutritional tracking, longitudinal progress monitoring, and behavioral gamification.`,
    explain_body_comp: (ctx) => `Body composition quantifies the lean mass to fat mass ratio. Your score of ${ctx.bodyScore}/100 reflects estimated composition quality. More accurate measurement requires DEXA or hydrostatic weighing; this system provides useful estimation.`,
    explain_muscle_dist: (ctx) => `Muscle tone distribution analysis segments lean mass estimates by body region. Identifies hypertrophic asymmetries and underdeveloped muscle groups for targeted programming.`,
    explain_posture_analysis: (ctx) => `Postural analysis score: ${ctx.postureScore}/100. Derived from glenohumeral horizontal alignment, cervical spine position, and pelvic tilt estimation via landmark triangulation.`,
    explain_body_zones: (ctx) => `Zone analysis segments the body into functional regions (upper, core, lower) with individual composition estimates. Enables targeted training prioritization based on regional deficits.`,
    explain_fitness_index: (ctx) => `Fitness Index: ${ctx.fitnessIndex}. Composite metric integrating body composition score, muscle tone index, postural alignment, and symmetry measures. Higher values indicate superior overall physical conditioning.`,
    explain_workout_player: (ctx) => `Workout Player provides exercise execution guidance with biomechanically correct movement demos, parametric sets/reps/rest tracking, and form cues. Progressive overload tracking is built in.`,
    explain_streaks_badges: (ctx) => `Streak metrics: consecutive daily adherence counter. Behavioral consistency data shows streaks correlate with long-term habit formation (habit loop theory). Badges provide threshold-based milestone reinforcement.`,
    explain_confidence_indicator: (ctx) => `Confidence indicator quantifies analysis reliability based on image quality metrics, landmark detection confidence scores, and available anthropometric input data.`,
    explain_visual_age: (ctx) => `Visual Age: composite estimate of physiological age based on body composition, postural alignment, and muscle tone metrics. Favorable composition indices correlate with lower visual age estimates.`,
    explain_symmetry: (ctx) => `Symmetry score quantifies bilateral muscle balance and proportional harmony using shoulder-to-waist ratio, limb circumference comparisons, and overall structural proportion indices.`,
    explain_ai_reasoning: (ctx) => `AI Reasoning toggle exposes the calculation methodology behind each score -- which landmark measurements were used, what ratios were calculated, and how they mapped to the output. Full algorithmic transparency.`,
    explain_scenarios: (ctx) => `Lifestyle Scenarios apply different activity multipliers and metabolic models to project outcomes: Active (1.55 TDEE multiplier), Sedentary (1.2), Intensive Training (1.725), Nutrition-Optimized (precision macro targets).`,
    explain_weekly_routine: (ctx) => `Weekly Routine generator applies volume landmarks (10-20 sets/muscle group/week) and frequency optimization (2x/week per muscle group) to design your personalized training split.`,
    explain_todays_routine: (ctx) => `Today's Routine maps your current training split to the day's scheduled muscle groups. Adapts to your weekly training frequency input.`,
    explain_food_recognition: (ctx) => `Food recognition uses computer vision to identify foods and estimate macronutrient composition from a photograph. Accuracy varies by food complexity -- single-ingredient foods yield higher precision.`,
    explain_meal_plan: (ctx) => `Meal Plan generation applies your TDEE, macronutrient targets, and dietary constraints to produce structured daily eating plans aligned with your body composition goals.`,
    explain_daily_macros: (ctx) => `Daily Macro Targets display: TDEE-calculated calorie goal with protein, carbohydrate, and fat targets. Progress visualization shows adherence percentage using logged intake data.`,
    explain_nutrition_insights: (ctx) => `Nutrition insights apply evidence-based protocols: protein distribution (20-40g leucine-optimized doses), meal timing (3-4 hour intervals for MPS optimization), hydration (35ml/kg bodyweight baseline).`,
    explain_exercise_filters: (ctx) => `Exercise filters allow stratification by training environment, experience level (beginner/intermediate/advanced), and target muscle group. Enables context-appropriate exercise selection.`,
    explain_themes: (ctx) => `Theme system applies CSS custom properties for visual customization. Multiple color schemes available -- visual preference has no performance impact but may improve adherence through environmental satisfaction.`,
    explain_body_silhouette: (ctx) => `Body silhouette provides a visual overlay mapping zone scores to anatomical regions. Spatial representation of body composition data aids in identifying regional training priorities.`,
    explain_coach_personas: (ctx) => `4 coaching modalities: Encouraging (motivational framing), Drill Sergeant (accountability-focused), Scientific (evidence-based precision), Casual (barrier reduction). Select based on your optimal motivation profile.`,
    explain_bmr_tdee: (ctx) => `BMR: Mifflin-St Jeor equation for resting energy expenditure. TDEE: BMR × activity multiplier. These values set your caloric baseline -- all nutrition targets derive from TDEE.`,
    explain_daily_habits: (ctx) => `Daily Habits: 5-item behavioral adherence tracker (workout, food log, hydration, sleep, coach interaction). Habit completion rate correlates with outcome achievement in behavioral health research.`,
    explain_sleep_tracker: (ctx) => `Sleep tracker logs duration and quality (subjective). Sleep is the primary recovery window: growth hormone release, muscle protein synthesis, and neural consolidation all peak during deep sleep phases.`,
    explain_weekly_report: (ctx) => `Weekly Report Card: composite performance metric across workout adherence, nutrition consistency, sleep quality, and habit completion. Trend analysis over multiple weeks provides the most statistically reliable performance indicator.`,
    explain_smart_insights: (ctx) => `Smart Insights applies pattern recognition to your longitudinal logged data. Surfaces behavioral correlations, consistency gaps, and performance anomalies that may not be apparent from individual data points.`,
    explain_calorie_balance: (ctx) => `Calorie Balance: daily energy intake minus estimated expenditure. Positive balance → mass gain. Negative balance → mass loss. Net calorie tracking over 7-day windows is more predictive than single-day snapshots.`,
    explain_hydration_history: (ctx) => `Hydration History: 7-day water intake visualization. Chronic mild dehydration (1-2% body weight) reduces athletic performance by 2-3% and cognitive function measurably. Consistent hydration tracking enables early intervention.`,
    explain_progress_charts: (ctx) => `Progress Charts: longitudinal visualization of body score, weight, sleep, activity, and caloric data. Trend analysis across multiple data points provides statistically reliable progress assessment -- single measurements have high variance.`,
    explain_challenges: (ctx) => `Challenges: structured behavioral targets with defined time windows. Operant conditioning via XP rewards reinforces target behaviors. Weekly reset maintains challenge salience and prevents habituation.`,
    explain_levels_xp: (ctx) => `XP system: cumulative engagement metric. Earned through defined behaviors (scans, food logs, coach queries, challenge completions). Level progression provides structured long-term motivation via intermittent reinforcement.`,
    explain_weight_log: (ctx) => `Weight logging enables trend analysis via moving averages, smoothing day-to-day fluctuations from hydration, glycogen, and digestive contents. 7-day moving average is most reliable for true fat/muscle change assessment.`,
    explain_goal_weight: (ctx) => `Goal Weight tracker calculates rate of progress from logged weight data and projects time-to-goal using linear regression on recent trend. Rate assumption: 0.5-1% bodyweight/week is physiologically sustainable.`,
    explain_food_log: (ctx) => `Food log enables precise macronutrient tracking. Systematic logging (>80% meal capture rate) is strongly correlated with body composition goal achievement across research literature.`,
    explain_workout_splits: (ctx) => `Training splits distribute volume for optimal recovery. Evidence-based selection: Full Body (2-3x/week, best for beginners), Upper/Lower (4x/week, intermediate), Push/Pull/Legs (6x/week, advanced).`,
    explain_body_recomp: (ctx) => `Body recomposition: simultaneous fat oxidation and muscle protein accrual. Physiologically achievable, particularly in untrained individuals. Requires precise energy balance (~maintenance) and adequate protein (1.6-2.2g/kg).`,
    explain_maintenance: (ctx) => `Maintenance phase: caloric intake matches TDEE. Physiological rationale: allows hormonal recovery, reduces metabolic adaptation, and consolidates training adaptations before subsequent phase.`,
    explain_workout_history: (ctx) => `Workout History logs completed training sessions with exercise, sets, reps, and load data. Longitudinal review enables training volume analysis and progressive overload verification.`,
    explain_personal_records: (ctx) => `Personal Records track peak performance per exercise (estimated 1RM or best logged set). Progressive improvement in PRs is the primary objective indicator of neuromuscular adaptation and strength development.`,
    explain_body_measurements: (ctx) => `Body Measurements tracks anthropometric circumferences (chest, waist, hips, arms). Combined with weight data, these measurements provide more informative body composition change indicators than weight alone -- particularly useful for detecting recomposition.`,
    explain_account: (ctx) => `My Account modal (user menu → My Account) allows modification of: display name, email, fitness profile parameters (height, weight, gender, age range, activity level, fitness goal), password, and account deletion. Accurate biometric data improves algorithmic output precision.`,
    explain_optional_measurements: (ctx) => `Optional anthropometric inputs (chest, waist, hips, arms in cm) supplement photo-based landmark detection with direct measurement data, improving body composition estimation accuracy. Measurement protocol: relaxed stance, tape perpendicular to body axis at widest circumference point.`,
    explain_export: (ctx) => `Export Data (Results screen) outputs a structured file of complete analysis metrics. Share Card generates a formatted summary visualization optimized for sharing. Share Workout creates a post-session summary. All export functions accessible via Results screen and Workout Player completion screen.`,
    explain_comparison: (ctx) => `Comparison modal: Progress → Scan History → select 2 scans → Compare. Displays differential analysis across all computed metrics: body composition score, muscle tone distribution, posture alignment, plus change percentages. Use for longitudinal body composition change assessment.`,
    explain_live_posture: (ctx) => `Live Posture Check (Workout screen → "Start Live Posture Check") activates device camera with MediaPipe Pose for real-time kinematic assessment. Evaluates shoulder alignment, spinal curvature, and hip positioning continuously, providing corrective cue overlays as proprioceptive feedback.`,
    explain_data_management: (ctx) => `"Clear All Data" is located in the Danger Zone (Profile Settings → My Account, scroll to bottom). Function: removes client-side session state, scan history, and log data. Scope: local storage only. Server-side account data is retained unless explicitly deleted via account deletion.`,
    explain_auth: (ctx) => `Authentication flow: Register (email + password + display name) → email verification → login. Existing users: direct credential-based login. Password recovery: "Forgot Password" → email-based reset link. Account benefits: server-side data persistence, cross-session synchronization.`,
    default: (ctx) => `I can provide evidence-based analysis on body composition, exercise physiology, and nutritional science. Please specify your query for optimal response precision.`,
  },

  casual: {
    greeting: (ctx) => `Hey! What's up? I'm your chill fitness buddy. Ask me anything -- no judgment, just good vibes and helpful tips!`,
    thanks: (ctx) => `No worries! That's what I'm here for. Hit me up anytime!`,
    help: (ctx) => `I can chat about your body score, workouts, food stuff, how the app works, or just general fitness vibes. What's on your mind?`,
    identity: (ctx) => `I'm basically your fitness buddy who lives in the app! I know about your analysis, can suggest workouts, talk nutrition, and help you figure out all the features.`,
    body_score: (ctx) => `So your body score is ${ctx.bodyScore} out of 100 -- you're in the "${ctx.category}" zone. Grade: ${ctx.grade}. Pretty interesting starting point!`,
    body_category: (ctx) => `You're in the "${ctx.category}" category with a ${ctx.bodyType} build. Pretty interesting, right?`,
    muscle_tone: (ctx) => `Muscle tone's at ${ctx.muscleScore}%. ${ctx.muscleScore < 40 ? 'Room to grow -- that\'s exciting!' : 'Looking solid!'}`,
    posture: (ctx) => `Posture score: ${ctx.postureScore}/100. ${ctx.postureScore < 60 ? 'Could use some work, but most of us are hunched over phones all day!' : 'Not bad at all!'}`,
    bmi: (ctx) => ctx.bmi ? `BMI is ${ctx.bmi}. Just one number though -- your full body score (${ctx.bodyScore}) is way more interesting.` : `No BMI yet -- pop in your height and weight for more info!`,
    confidence: (ctx) => `Confidence is "${ctx.confidence}" -- basically how much the AI trusts its own analysis. Better photo = better confidence!`,
    goal: (ctx) => `Your goal is set to ${GOAL_LABELS[ctx.goal] || 'general fitness'}. Everything in the app adjusts to help you nail that!`,
    lose_weight: (ctx) => `For losing weight: eat a bit less than you burn, keep protein up, lift some weights, and be patient. You don't need to suffer -- just be consistent!`,
    build_muscle: (ctx) => `Wanna get bigger? Eat a little more, hit the weights, focus on getting stronger over time, and SLEEP. That's basically it!`,
    improve_posture: (ctx) => `For better posture: rows, face pulls, stretch your chest. Wall angels are weirdly effective. 5 minutes a day makes a real difference!`,
    workout_general: (ctx) => `Check out the Workout screen -- it's got exercises picked just for you based on your score of ${ctx.bodyScore}!`,
    workout_plan: (ctx) => `Head to the Workout screen! There's a full plan waiting for you based on your goals and body type.`,
    workout_frequency: (ctx) => `3-5 days a week is the sweet spot for most people. Rest days matter too -- that's when your muscles actually grow!`,
    workout_reps: (ctx) => `For building muscle: 8-12 reps works great. For strength: go heavy with 3-5. Mix it up and keep things interesting!`,
    cardio: (ctx) => `2-3 cardio sessions per week, 20-30 minutes. Doesn't have to be running -- dance, bike, swim, whatever you enjoy!`,
    nutrition_general: (ctx) => `Food is fuel! Check out the Nutrition screen for your personalized targets. Don't overthink it -- just try to eat good food most of the time.`,
    protein: (ctx) => `Protein is your best friend for fitness goals. Aim for about 0.8g per pound of bodyweight. Chicken, eggs, fish, Greek yogurt -- all the good stuff!`,
    calories: (ctx) => `Calories matter but don't stress about being perfect. Get in the ballpark and focus on making good choices most of the time.`,
    macros: (ctx) => `Think of macros as: protein first (it's most important), then fat and carbs fill the rest. Pretty simple once you get the hang of it!`,
    how_it_works: (ctx) => `The app takes your photo, finds 33 body landmarks using AI, and calculates your body ratios and proportions. It's pretty cool tech -- and it's all free!`,
    what_is_this: (ctx) => `Fix-it is basically a body analysis app! Upload a photo, get a full breakdown of your body composition, then use that to guide your workouts and nutrition. Simple and powerful!`,
    cycle_workout: (ctx) => `During your period, feel free to dial it back if you need to! Light movement can actually help with cramps. Just listen to your body and don't stress if you're not at 100%.`,
    cycle_for_other: (ctx) => `Totally! Have them upload their own photo and go through the same flow. The app will give them their own personalized analysis and recommendations.`,
    explain_upload: (ctx) => `The Upload screen is super easy -- just take a photo (front-facing, decent lighting, full body) and the AI does the rest! Better photo quality = more accurate results.`,
    explain_results: (ctx) => `The Results screen shows your body score, grade, muscle tone, posture, BMI, and more. It's basically your fitness report card!`,
    explain_breakdown: (ctx) => `Breakdown goes deeper -- it shows you zone-by-zone scores for upper body, core, and lower body. Great for figuring out what to focus on!`,
    explain_simulator: (ctx) => `The Simulator is so fun! It shows what you could look like after consistent effort. Drag the timeline to see 1 month, 3 months, 6 months of progress. Very motivating!`,
    explain_workout_screen: (ctx) => `The Workout screen has exercises tailored for you! Filter by home or gym, pick your difficulty, and tap any exercise to start a guided session with a timer. Super handy!`,
    explain_nutrition_screen: (ctx) => `Nutrition screen shows your macro targets, lets you log food, snap meals for auto-logging, and gives you science-based eating tips. It's like having a nutritionist in your pocket!`,
    explain_progress_screen: (ctx) => `Progress screen is the most fun! Streaks, badges, XP, level system, challenges, scan history, weekly report, sleep tracker, charts... it's all there. Very satisfying to fill up!`,
    explain_scan_history: (ctx) => `Scan History saves all your analyses! Tap two scans to compare them side by side and see how much you've changed. The before-and-after view is SO motivating!`,
    app_features: (ctx) => `The app has 7 screens: Upload (take a photo), Results (your scores), Breakdown (zone detail), Simulator (future body preview), Workout (guided exercises), Nutrition (food tracking), and Progress (streaks + history). Each one is awesome!`,
    explain_body_comp: (ctx) => `Body composition is basically the balance between your fat and muscle. Your score of ${ctx.bodyScore} shows how that balance looks right now -- and it's totally improvable!`,
    explain_muscle_dist: (ctx) => `Muscle distribution shows which parts of your body have more developed muscle. Super useful for seeing if you're balanced or if one area needs more love!`,
    explain_posture_analysis: (ctx) => `Posture analysis looks at how you're aligned -- shoulders, spine, hips. Score of ${ctx.postureScore}/100. Most people can improve this a lot just with targeted exercises!`,
    explain_body_zones: (ctx) => `Body zones split you into upper, core, and lower sections with separate scores. It's like a map showing where to focus your energy -- really helpful for targeted training!`,
    explain_fitness_index: (ctx) => `The Fitness Index (${ctx.fitnessIndex}) is like one overall number that sums up your whole body -- composition, muscle, posture, everything. Fun number to try to improve!`,
    explain_workout_player: (ctx) => `The Workout Player guides you through exercises with animated demos and timers. Tap Start on any exercise and just follow along -- it's like having a personal trainer!`,
    explain_streaks_badges: (ctx) => `Streaks track how many days in a row you've been showing up! Badges pop up for cool milestones. It's weirdly addictive to keep that streak going!`,
    explain_confidence_indicator: (ctx) => `Confidence shows how reliable your analysis is. Better photo (good lighting, full body, front-facing) = higher confidence = more accurate results!`,
    explain_visual_age: (ctx) => `Visual Age is an estimate of how old your body looks based on your fitness. Being consistent can actually make it drop -- your body can look younger than you are!`,
    explain_symmetry: (ctx) => `Symmetry measures how balanced your body proportions are. A higher score means you're well-balanced! Asymmetries often come from favoring one side in training.`,
    explain_ai_reasoning: (ctx) => `The AI Reasoning toggle explains why the app gave you each score. Super interesting to see the logic! It helps you understand exactly what the AI is looking at.`,
    explain_scenarios: (ctx) => `Scenarios in the Simulator let you see different "what if" paths -- what if you're super active? What if you focus on nutrition? Compare them and pick your favorite future!`,
    explain_weekly_routine: (ctx) => `The Weekly Routine generator builds your whole training split! Just say how many days you want to train and it designs Push/Pull/Legs, Upper/Lower, or Full Body for you. Easy!`,
    explain_todays_routine: (ctx) => `Today's Routine tells you exactly what muscle groups to train today based on your split. No thinking required -- just open the app and see what's up!`,
    explain_food_recognition: (ctx) => `Snap Your Meal is SO cool -- take a photo of your food and the AI estimates the macros! Great for when you don't want to manually search for everything you ate.`,
    explain_meal_plan: (ctx) => `The Meal Plan generator creates a full day of meal suggestions just for you! Pick your dietary preference (veggie, high protein, low carb) and it builds your menu. Meal prep made easy!`,
    explain_daily_macros: (ctx) => `Daily Macros shows your calorie and protein/carb/fat goals with progress bars. There's even a circular chart showing how on-track you are overall. Weirdly satisfying to fill it up!`,
    explain_nutrition_insights: (ctx) => `Nutrition Insights gives you three handy tips: when to eat your protein, how often to eat, and how much water to drink. Science-backed but easy to actually follow!`,
    explain_exercise_filters: (ctx) => `Exercise filters let you find the perfect workout for your situation -- at home or the gym, beginner or advanced, targeting specific weak areas. Super customizable!`,
    explain_themes: (ctx) => `Themes let you change the whole look of the app! There are 5 options from dark charcoal to bright ivory. Find your vibe and make it yours!`,
    explain_body_silhouette: (ctx) => `The Body Silhouette is basically a body map with your scores overlaid on each zone. Really visual and intuitive -- at a glance you can see where you're strong and where to improve!`,
    explain_coach_personas: (ctx) => `There are 4 coach styles to pick from! Encouraging (super supportive), Drill Sergeant (tough love), Scientific (all the data), and Casual (hey that's me!). Switch anytime from the coach panel.`,
    explain_bmr_tdee: (ctx) => `BMR is how many calories you burn just existing. TDEE is your total daily burn including activity. Your nutrition targets are based on TDEE -- pretty important number to know!`,
    explain_daily_habits: (ctx) => `Daily Habits tracks 5 things every day: workout logged, food logged, water goal met, sleep logged, and coach consulted. Hit all 5 and you get a perfect daily score. Super satisfying!`,
    explain_sleep_tracker: (ctx) => `Sleep Tracker lets you log how much you slept and how well. Sleep is honestly huge for fitness -- that's when muscles repair and grow. Log it every morning and watch the habit build!`,
    explain_weekly_report: (ctx) => `The Weekly Report Card grades your whole week! Workouts, nutrition, sleep, habits -- all rolled into one letter grade. It's like a report card but for your health. Makes you wanna get an A!`,
    explain_smart_insights: (ctx) => `Smart Insights is like having a data analyst look at your logs and spot patterns. Maybe you always skip water on Tuesdays, or you sleep great on workout days. Really eye-opening stuff!`,
    explain_calorie_balance: (ctx) => `Calorie Balance shows how much you ate vs. how much you burned today. It's the clearest way to see if you're on track for your goal. Simple and useful!`,
    explain_hydration_history: (ctx) => `Hydration History shows your water intake as a heatmap over the last 7 days. It's so satisfying when all the cells are full! Helps you spot when you tend to slack on water.`,
    explain_progress_charts: (ctx) => `Progress Charts show your data over time -- weight, sleep, calories, body score. Each tab shows a trend line so you can actually SEE your improvement. So motivating!`,
    explain_challenges: (ctx) => `Challenges are fun weekly missions -- like "log 3 workouts" or "ask the coach 5 questions". Finish them and you get XP! Progress tab has all your active ones.`,
    explain_levels_xp: (ctx) => `XP is basically your fitness score in the app! You earn it by doing stuff -- scanning, logging food, finishing challenges. Stack enough and you level up. Pretty satisfying!`,
    explain_weight_log: (ctx) => `Weight Log is super simple -- just punch in your weight for today and it tracks the trend over time. Find it in the Progress screen!`,
    explain_goal_weight: (ctx) => `Goal Weight shows you the journey from where you started to where you want to be, with a progress bar and weeks estimate. So cool to watch it move as you log!`,
    explain_food_log: (ctx) => `Food Log lets you track everything you eat so you can see your daily macros. Logging consistently is honestly the biggest cheat code for hitting your goals!`,
    explain_workout_splits: (ctx) => `Workout splits are how you divide your training days! Push/Pull/Legs, Upper/Lower, Full Body -- check the Workout screen for your personalized recommendation!`,
    explain_body_recomp: (ctx) => `Body recomp is losing fat and gaining muscle at the same time -- it's totally possible! Keep calories around maintenance, eat loads of protein, and lift heavy. Slow but worth it!`,
    explain_maintenance: (ctx) => `Maintenance just means eating enough to stay at your current weight -- not gaining, not losing. Great for a break between cut and bulk phases!`,
    explain_workout_history: (ctx) => `Workout History keeps a log of every session you complete! You can see what you did, when you did it, and how it adds up over time. Super satisfying to scroll through a full history!`,
    explain_personal_records: (ctx) => `Personal Records are your best lifts! Every time you beat your previous best on an exercise, it gets saved here. Watching your PRs go up over time is one of the most motivating things in fitness!`,
    explain_body_measurements: (ctx) => `Body Measurements lets you track your chest, waist, hips, and arms over time. Great for when the scale isn't budging but you know your clothes are fitting differently. The real progress is in the tape!`,
    explain_account: (ctx) => `Super easy — tap your name or avatar in the top right and hit "My Account"! You can update your name, email, fitness stats like height/weight/goal, change your password, or delete your account. Keep those fitness details fresh for better recommendations!`,
    explain_optional_measurements: (ctx) => `Those optional measurements on the upload screen are actually really helpful! Just grab a regular soft tape measure and enter your chest, waist, hips, and arms in cm. The AI uses them to get a way more accurate read on your body shape. Takes like 2 minutes and makes the results noticeably better!`,
    explain_export: (ctx) => `After your analysis, the Results screen has "Export Data" to save your stats and "Share Card" to make a cool shareable image of your results. Once you finish a workout in the player, you can hit "Share Workout" too. Great for keeping yourself accountable or just showing off your progress!`,
    explain_comparison: (ctx) => `Super cool feature! Go to the Progress screen, scroll down to Scan History, and select two scans. Hit Compare and you get a side-by-side view of all your stats — body score, muscle tone, posture — with the changes shown. Really satisfying to see the before vs after difference!`,
    explain_live_posture: (ctx) => `Oh this feature is cool! On the Workout screen, tap "Start Live Posture Check" and it'll use your camera to check your posture in real time. It spots if your shoulders, spine, or hips are out of alignment and gives you correction tips. Super handy while actually working out!`,
    explain_data_management: (ctx) => `The "Clear All Data" button is now in the Danger Zone at the bottom of Profile Settings (tap your avatar → My Account)! It wipes your local scan history, logs, and session data. Your actual account stays intact — it's just local data!`,
    explain_auth: (ctx) => `Signing up is super easy! Hit "Sign Up", enter your email and a password, pick a display name, then check your email to verify. After that, just log in and you're good! Forgot your password? No worries — "Forgot Password" sends a reset email. Having an account means your progress saves across sessions!`,
    default: (ctx) => `Hmm, not sure about that one! Try asking about your body score, workouts, nutrition, or how the app works. I'm pretty good at those!`,
  },
};

function generateResponse(intent, persona, ctx) {
  const personaResponses = RESPONSES[persona] || RESPONSES.encouraging;
  const fn = personaResponses[intent] || personaResponses.default || RESPONSES.encouraging.greeting;
  return typeof fn === 'function' ? fn(ctx) : fn;
}

async function processMessage(userId, message, persona) {
  const intent = detectIntent(message) || 'greeting';
  const ctx = await buildContext(userId);
  const response = generateResponse(intent, persona, ctx);
  return { intent, response };
}

module.exports = { processMessage };
